/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import static ventanas.ModificarUsuarios.user_update;

/**
 *
 * @author Asus
 */
public class GestionarClientes extends javax.swing.JFrame {
    
    String user;
    public static int IDcliente_update;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form GestionarClientes
     */
    public GestionarClientes() {
        initComponents();
        user = Login.user;
        
        setSize(660, 460);
        setResizable(false);
        setTitle("Recepcionista - Sesión de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpapertech.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try{
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select id_cliente, nombre_cliente, rut_cliente, email_cliente, telefono_cliente, ult_modificacion from clientes");
            
            ResultSet rs = pst.executeQuery();
            
            jTable_clientes = new JTable(model);
            jScrollPane1.setViewportView(jTable_clientes);
            
            model.addColumn(" ");
            model.addColumn("Nombre");
            model.addColumn("RUT");
            model.addColumn("Email");
            model.addColumn("Telefono");
            model.addColumn("Modificado Por");
            
            while (rs.next()) {
                Object[] fila = new Object[6];

                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }

                model.addRow(fila);

            }

            cn.close();
            
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla" + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion, contacta a un administrador");
        }
        
        ObtenerDatosTabla();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo_TechSinFondo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_clientes = new javax.swing.JTable();
        jLabel_Footer = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        txt_buscarNombre = new javax.swing.JTextField();
        txt_buscarRUT = new javax.swing.JTextField();
        jLabel_buscarRUT = new javax.swing.JLabel();
        jLabel_buscarNombre = new javax.swing.JLabel();
        jLabel_buscar = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jTable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_clientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 660, 180));

        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setText("Lista de usuarios registrados");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        Buscar.setBackground(new java.awt.Color(153, 153, 240));
        Buscar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar");
        Buscar.setBorder(null);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 210, 35));

        txt_buscarNombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_buscarNombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_buscarNombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_buscarNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_buscarNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 210, -1));

        txt_buscarRUT.setBackground(new java.awt.Color(153, 153, 255));
        txt_buscarRUT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_buscarRUT.setForeground(new java.awt.Color(255, 255, 255));
        txt_buscarRUT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_buscarRUT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_buscarRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, -1));

        jLabel_buscarRUT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_buscarRUT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_buscarRUT.setText("RUT:");
        getContentPane().add(jLabel_buscarRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel_buscarNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_buscarNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_buscarNombre.setText("Nombre:");
        getContentPane().add(jLabel_buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_buscar.setText("Buscar Cliente por:");
        getContentPane().add(jLabel_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

        String buscarRUT = txt_buscarRUT.getText().trim();
        String buscarNombre = txt_buscarNombre.getText().trim();
        String query = "";

        model.setRowCount(0);
        model.setColumnCount(0);

        try {
            Connection cn2 = Conexion.conectar();

            if (buscarRUT.equals("") && buscarNombre.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar uno de los valores para poder buscar un cliente especifico");
                query = "select id_cliente, nombre_cliente, rut_cliente, email_cliente, telefono_cliente, ult_modificacion from clientes";
            } else if (buscarNombre.equals("")) {
                query = "select id_cliente, nombre_cliente, rut_cliente, email_cliente, telefono_cliente, ult_modificacion from clientes where rut_cliente = '" + buscarRUT + "'";
            } else if (buscarRUT.equals("")) {
                query = "select id_cliente, nombre_cliente, rut_cliente, email_cliente, telefono_cliente, ult_modificacion from clientes where nombre_cliente = '" + buscarNombre + "'";
            } else {
                query = "select id_cliente, nombre_cliente, rut_cliente, email_cliente, telefono_cliente, ult_modificacion from clientes where rut_cliente = '" + buscarRUT + "' and nombre_cliente = '" + buscarNombre + "'";

            }

            PreparedStatement pst2 = cn2.prepareStatement(query);
            ResultSet rs2 = pst2.executeQuery();

            jTable_clientes = new JTable(model);
            jScrollPane1.setViewportView(jTable_clientes);
            
            model.addColumn(" ");
            model.addColumn("Nombre");
            model.addColumn("RUT");
            model.addColumn("Email");
            model.addColumn("Telefono");
            model.addColumn("Modificado Por");

            while (rs2.next()) {
                Object[] fila = new Object[6];

                for (int i = 0; i < 6; i++) {
                    fila[i] = rs2.getObject(i + 1);
                }

                model.addRow(fila);

            }

            cn2.close();

            Limpiar();

        } catch (SQLException e) {
            System.err.println("Error al recuperar los registros de clientes. Boton Buscar " + e);
        }
        
        ObtenerDatosTabla();

    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_buscar;
    private javax.swing.JLabel jLabel_buscarNombre;
    private javax.swing.JLabel jLabel_buscarRUT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_clientes;
    private javax.swing.JTextField txt_buscarNombre;
    private javax.swing.JTextField txt_buscarRUT;
    // End of variables declaration//GEN-END:variables

    public void ObtenerDatosTabla(){
        jTable_clientes.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = jTable_clientes.rowAtPoint(e.getPoint());
                int columna_point = 0;
                
                if(fila_point > -1){
                    IDcliente_update = (int)model.getValueAt(fila_point, columna_point);
                    Informacion_Cliente informacion_cliente = new Informacion_Cliente();
                    informacion_cliente.setVisible(true);
                }
                
            }
        });
    }
    
    public void Limpiar() {
        txt_buscarRUT.setText("");
        txt_buscarNombre.setText("");

    }

}
