/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Asus
 */
public class Informacion_Insumo extends javax.swing.JFrame {
    
    String user;
    int IDinsumo = 0;

    /**
     * Creates new form RegistrarClientes
     */
    public Informacion_Insumo() {
        initComponents();
        user = Login.user;
        IDinsumo = GestionarInsumos.IDinsumo_update;
        
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from insumo where id_insumo = '" + IDinsumo + "'");

            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txt_nombreInsumo.setText(rs.getString("nombre_insumo"));
                txt_marcaInsumo.setText(rs.getString("marca_insumo"));
                txt_modeloInsumo.setText(rs.getString("modelo_insumo"));
                cmb_tipoequipo.setSelectedItem(rs.getString("repuesto_para"));
                txt_serieInsumo.setText(rs.getString("num_serie_insumo"));
                txt_cantidadInsumo.setText(rs.getString("cantidad"));
            }
            
        }catch (SQLException e){
            System.err.println("Error al consultar la informacion del equipo" + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar la informacion, contacte a un administrador");
        }
        
        setTitle("Insumo registrado con el ID " + IDinsumo + " - Sesión de " + user);
        setSize(530,430);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpapertech.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo_TechSinFondo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreInsumo = new javax.swing.JTextField();
        txt_modeloInsumo = new javax.swing.JTextField();
        txt_serieInsumo = new javax.swing.JTextField();
        jButton_ActualizarInsumo = new javax.swing.JButton();
        jLabel_Footer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_marcaInsumo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cantidadInsumo = new javax.swing.JTextField();
        cmb_tipoequipo = new javax.swing.JComboBox<>();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del Insumo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Del insumo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo del insumo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repuestos para:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de serie:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Actualizar Informacion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        txt_nombreInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombreInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_modeloInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modeloInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modeloInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modeloInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modeloInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txt_serieInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_serieInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_serieInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serieInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_serieInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, -1));

        jButton_ActualizarInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jButton_ActualizarInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarInsumoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ActualizarInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 140, 80));

        jLabel_Footer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setText("Informacion Insumo");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca del insumo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_marcaInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_marcaInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_marcaInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_marcaInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_marcaInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        txt_cantidadInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_cantidadInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_cantidadInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidadInsumo.setText("0");
        txt_cantidadInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cantidadInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, -1));

        cmb_tipoequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Notebook", "Desktop", "Multifuncional", "Impresora", "Pantalla", "Escaner" }));
        getContentPane().add(cmb_tipoequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarInsumoActionPerformed

        int validacion = 0;
        String nombre_insumo, marca_insumo, modelo_insumo, repuesto_para, num_serie_insumo;
        int cantidad;
        
        nombre_insumo = txt_nombreInsumo.getText().trim();
        marca_insumo = txt_marcaInsumo.getText().trim();
        modelo_insumo = txt_modeloInsumo.getText().trim();
        repuesto_para = cmb_tipoequipo.getSelectedItem().toString();
        num_serie_insumo = txt_serieInsumo.getText().trim();
        cantidad = Integer.parseInt(txt_cantidadInsumo.getText());
        
        if(nombre_insumo.equals("")){
            txt_nombreInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(marca_insumo.equals("")){
            txt_nombreInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(modelo_insumo.equals("")){
            txt_nombreInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(num_serie_insumo.equals("")){
            txt_nombreInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(cantidad <= 0){
            txt_cantidadInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(validacion == 0){
            
            try{
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "update insumo set nombre_insumo=?, marca_insumo=?, modelo_insumo=?, repuesto_para=?, num_serie_insumo=?, cantidad=? "
                            + "where id_insumo = '" + IDinsumo + "'");
                
                pst.setString(1, nombre_insumo);
                pst.setString(2, marca_insumo);
                pst.setString(3, modelo_insumo);
                pst.setString(4, repuesto_para);
                pst.setString(5, num_serie_insumo);
                pst.setInt(6, cantidad);

                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                
                txt_nombreInsumo.setBackground(Color.green);
                txt_marcaInsumo.setBackground(Color.green);
                txt_modeloInsumo.setBackground(Color.green);
                txt_serieInsumo.setBackground(Color.green);
                txt_cantidadInsumo.setBackground(Color.green);
                
                JOptionPane.showMessageDialog(null, "Actualización correcta");
                this.dispose();
                
            }catch (SQLException e){
                System.err.println("Error en actualizar equipo " + e);
                JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar equipo!!, contacte a un administrador.");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
                

    }//GEN-LAST:event_jButton_ActualizarInsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_Insumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_Insumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_tipoequipo;
    private javax.swing.JButton jButton_ActualizarInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_cantidadInsumo;
    private javax.swing.JTextField txt_marcaInsumo;
    private javax.swing.JTextField txt_modeloInsumo;
    private javax.swing.JTextField txt_nombreInsumo;
    private javax.swing.JTextField txt_serieInsumo;
    // End of variables declaration//GEN-END:variables

    
    public void Limpiar(){
        txt_nombreInsumo.setText("");
        txt_marcaInsumo.setText("");
        txt_modeloInsumo.setText("");
        txt_cantidadInsumo.setText("");
        txt_serieInsumo.setText("");
    }
}
