/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Asus
 */
public class RegistrarInsumos extends javax.swing.JFrame {
    
    String user;

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarInsumos() {
        initComponents();
        user = Login.user;
        
        setTitle("Registrar nuevo Insumo - Sesión de " + user);
        setSize(530,430);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpapertech.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo_TechSinFondo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreInsumo = new javax.swing.JTextField();
        txt_modeloInsumo = new javax.swing.JTextField();
        txt_serieInsumo = new javax.swing.JTextField();
        jButton_RegistrarInsumo = new javax.swing.JButton();
        jLabel_Footer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_marcaInsumo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cantidadInsumo = new javax.swing.JTextField();
        cmb_tipoequipo = new javax.swing.JComboBox<>();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Insumos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Del insumo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo del insumo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repuestos para:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de serie:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar Insumo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        txt_nombreInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombreInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_modeloInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modeloInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modeloInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modeloInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modeloInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txt_serieInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_serieInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_serieInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serieInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_serieInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, -1));

        jButton_RegistrarInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pixlr-bg-result.png"))); // NOI18N
        jButton_RegistrarInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarInsumoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 120, 100));

        jLabel_Footer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel_Footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Footer.setText("Informacion Insumo");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca del insumo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_marcaInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_marcaInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_marcaInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_marcaInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_marcaInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        txt_cantidadInsumo.setBackground(new java.awt.Color(153, 153, 255));
        txt_cantidadInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txt_cantidadInsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidadInsumo.setText("0");
        txt_cantidadInsumo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cantidadInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, -1));

        cmb_tipoequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Notebook", "Desktop", "Multifuncional", "Impresora", "Pantalla", "Escaner" }));
        getContentPane().add(cmb_tipoequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarInsumoActionPerformed

        int validacion = 0;
        String nombreInsumo, marcaInsumo, modeloInsumo, repuesto_para, serieInsumo;
        int Cantidad;
        
        nombreInsumo = txt_nombreInsumo.getText().trim();
        marcaInsumo = txt_marcaInsumo.getText().trim();
        modeloInsumo = txt_modeloInsumo.getText().trim();
        repuesto_para = cmb_tipoequipo.getSelectedItem().toString();
        serieInsumo = txt_serieInsumo.getText().trim();
        Cantidad = Integer.parseInt(txt_cantidadInsumo.getText());
        
        if(nombreInsumo.equals("")){
            txt_nombreInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(marcaInsumo.equals("")){
            txt_marcaInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(modeloInsumo.equals("")){
            txt_modeloInsumo.setBackground(Color.red);
            validacion++;
        }
        if(serieInsumo.equals("")){
            txt_serieInsumo.setBackground(Color.red);
            validacion++;
        }
        if(Cantidad <= 0){
            txt_cantidadInsumo.setBackground(Color.red);
            validacion++;
        }
        
        if(validacion == 0){
            
            try{
                
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "insert into insumo values (?,?,?,?,?,?,?)");
                
                pst.setInt(1, 0);
                pst.setString(2, nombreInsumo );
                pst.setString(3, marcaInsumo);
                pst.setString(4, modeloInsumo);
                pst.setString(5, repuesto_para);
                pst.setString(6, serieInsumo);
                pst.setInt(7, Cantidad);
                
                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                
                txt_nombreInsumo.setBackground(Color.green);
                txt_marcaInsumo.setBackground(Color.green);
                txt_modeloInsumo.setBackground(Color.green);
                txt_cantidadInsumo.setBackground(Color.green);
                txt_serieInsumo.setBackground(Color.green);
                
                JOptionPane.showMessageDialog(null, "Registro exitoso");
                
                
            } catch (SQLException e) {
                System.out.println("Error en registrar cliente: " + e);
                JOptionPane.showMessageDialog(null, "¡¡Error en registrar usuario!! avisa a un administrador");
            }
            
        } else {
           JOptionPane.showMessageDialog(null, "Debes llenar todos los campos y no puedes ingresar valores menores a 1");
        }

    }//GEN-LAST:event_jButton_RegistrarInsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarInsumos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_tipoequipo;
    private javax.swing.JButton jButton_RegistrarInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_cantidadInsumo;
    private javax.swing.JTextField txt_marcaInsumo;
    private javax.swing.JTextField txt_modeloInsumo;
    private javax.swing.JTextField txt_nombreInsumo;
    private javax.swing.JTextField txt_serieInsumo;
    // End of variables declaration//GEN-END:variables

    
    public void Limpiar(){
        txt_nombreInsumo.setText("");
        txt_marcaInsumo.setText("");
        txt_modeloInsumo.setText("");
        txt_cantidadInsumo.setText("");
        txt_serieInsumo.setText("");
    }
}
